### ISSUE TITLE
pkginfo causes node server to crash when using webpack to bundle dependencies

### ISSUE THREAD

**Issue by ddlees** [Unleash/unleash-client-node#106] opened 2019-03-18 02:37 UTC
This issue stems from the unleash client use of the pkginfo module and consumers using a module bundler to inline their server dependencies.

https://github.com/Unleash/unleash-client-node/blob/f64df7e51818d6c0d19af44a6f0d9a92b48793d4/src/metrics.ts#L6

pkginfo attempts to locate the directory of the package.json as a convenience but doesn't play nice w/ webpack or other module bundlers and ultimately causes NodeJS to throw an error.

This fix here is pretty straight-forward. It's simply a matter of dropping pkginfo as a dependency and using relative paths to import the package.json. Cheers!

**Comment by ivarconr** [comment] 2019-03-18 10:17
Thanks for reporting this issue @ddlees!

> This fix here is pretty straight-forward. It's simply a matter of dropping pkginfo as a dependency and using relative paths to import the package.json. Cheers!

This was the first approach attempted. The problem is that it will not be as simple as this when it is included as a dependency in other projects. There where several cases where wrong version number was picked up (the wrapping project and not the unleash-client) 

I think a better approach will be to have a small script extracting this information build time. I will do a fix for this to remove the dependency.

**Comment by ddlees** [comment] 2019-03-18 13:23
Awesome, thanks @ivarconr!

**Closed** 2019-03-20 17:01 UTC

**Comment by ivarconr** [comment] 2019-03-20 17:19
fixed in 3.2.3

**Comment by ddlees** [comment] 2019-03-20 18:23
Thanks @ivarconr! You're the best!
